#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,math,os,statistics,sys
from pathlib import Path
import torch,yaml
WS=Path(__file__).resolve().parents[2];sys.path[:0]=[str(WS/'LIBERO'),str(WS/'lerobot/src'),str(WS)]
from research.coreact_closed_loop.guidance import tensor_sha256
from research.coreact_closed_loop.runtime import load_policy_and_processors,make_task_env,prepare
from research.coreact_dynamic_core.dynamic_guidance import COMMON_SELECTORS,sample_common_min_actions
def main():
 p=argparse.ArgumentParser();p.add_argument('--workspace',type=Path,required=True);p.add_argument('--artifact',type=Path,required=True);a=p.parse_args();w=a.workspace.resolve();art=a.artifact.resolve();protocol=yaml.safe_load((art/'protocol.lock.yaml').read_text());cap=protocol['operator']['magnitude_cap'];os.environ.setdefault('HF_HOME',str(w/'task1/.hf-cache'));os.environ.setdefault('TRANSFORMERS_CACHE',str(w/'task1/.hf-cache/hub'));os.environ['MUJOCO_GL']='egl'
 cfg,policy,pre,_=load_policy_and_processors(w);means=torch.load(w/'artifacts/coreact_exploration_v8_20260807_002951/modality_means.pt',weights_only=True,map_location='cpu')['visual_position_mean'];from libero.libero import benchmark;suite=benchmark.get_benchmark_dict()['libero_spatial']();language=suite.get_task(4).language;rows=[];repeat_pass=vanilla_parity=True
 for init in protocol['init_state_ids']:
  env,env_pre,_=make_task_env('libero_spatial',4,cfg)
  try:
   env.envs[0].init_state_id=init;obs,_=env.reset(seed=170004000+init);batch=prepare(policy,pre,env_pre,obs,language);g=torch.Generator(device=batch['state'].device).manual_seed(202608640000+init*1000);noise=torch.randn((1,cfg.chunk_size,cfg.max_action_dim),generator=g,device=batch['state'].device,dtype=batch['state'].dtype)
   outputs,traces=sample_common_min_actions(policy.model,batch['images'],batch['image_masks'],batch['lang_tokens'],batch['lang_masks'],batch['state'],noise,means,selection_seed=20270814+40000+init*100,magnitude_cap=cap);state=[]
   for name in COMMON_SELECTORS:
    tr=traces[name];steps=tr['step_traces'];state.append({'selector':name,'selected_indices':tr['selected_indices'],'changed_indices':tr['changed_indices'],'postclip_rms':math.sqrt(statistics.mean(x['applied_guidance_norm']**2 for x in steps)),'alpha_median':statistics.median(x['alpha'] for x in steps),'common_over_attention_median':statistics.median(x['common_over_attention'] for x in steps),'clipping_fraction':statistics.mean(x['clipped'] for x in steps),'extrapolation_count':sum(x['extrapolated'] for x in steps),'output_sha256':tensor_sha256(outputs[name]),'clean_flow_final_sha256':tr['clean_flow_final_sha256'],'finite':tr['all_output_finite'],'protected':tr['protected_tokens_untouched'],'step_traces':steps})
   if init==0:
    vanilla=policy.model.sample_actions(batch['images'],batch['image_masks'],batch['lang_tokens'],batch['lang_masks'],batch['state'],noise=noise);vanilla_parity=state[0]['clean_flow_final_sha256']==tensor_sha256(vanilla);outputs2,traces2=sample_common_min_actions(policy.model,batch['images'],batch['image_masks'],batch['lang_tokens'],batch['lang_masks'],batch['state'],noise,means,selection_seed=20270814+40000,magnitude_cap=cap);repeat_pass=all(state[i]['selected_indices']==traces2[name]['selected_indices'] and state[i]['output_sha256']==tensor_sha256(outputs2[name]) for i,name in enumerate(COMMON_SELECTORS))
   payload={'task_id':4,'init_state_id':init,'selectors':state};(art/'phase0_states'/f'task04__init{init:02d}.json').write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');rows.append(payload);print(json.dumps({'phase0_complete':len(rows),'planned':50,'init':init}),flush=True)
  finally:env.close()
 flat=[x for r in rows for x in r['selectors']];ratios={s:statistics.median(next(x for x in r['selectors'] if x['selector']==s)['postclip_rms']/next(x for x in r['selectors'] if x['selector']=='attention')['postclip_rms'] for r in rows) for s in ('random','instability')};common_ratio=statistics.median(x['common_over_attention_median'] for x in flat if x['selector']=='attention');perstep=max(abs(a['applied_guidance_norm']-b['applied_guidance_norm'])/max(a['applied_guidance_norm'],1e-12) for r in rows for a,b in zip(next(x for x in r['selectors'] if x['selector']=='random')['step_traces'],next(x for x in r['selectors'] if x['selector']=='attention')['step_traces']))
 gate={'states_complete':len(rows)==50,'exact8_protected':all(len(x['selected_indices'])==8 and sorted(x['selected_indices'])==sorted(x['changed_indices']) and x['protected'] for x in flat),'finite':all(x['finite'] for x in flat),'clean_hash_identity':all(len({x['clean_flow_final_sha256'] for x in r['selectors']})==1 for r in rows),'vanilla_clean_parity':vanilla_parity,'deterministic_repeat':repeat_pass,'rms_ratios_to_attention':ratios,'rms_match_pass':all(.999<=x<=1.001 for x in ratios.values()),'max_per_step_relative_error':perstep,'per_step_match_pass':perstep<=1e-5,'alpha_cap_pass':all(all(z['alpha']<=1+1e-8 for z in x['step_traces']) for x in flat),'extrapolation_count':sum(x['extrapolation_count'] for x in flat),'median_common_over_attention':common_ratio,'strength_pass':common_ratio>=.8};gate['pass']=all(gate[k] for k in ('states_complete','exact8_protected','finite','clean_hash_identity','vanilla_clean_parity','deterministic_repeat','rms_match_pass','per_step_match_pass','alpha_cap_pass','strength_pass')) and gate['extrapolation_count']==0
 decision='COMMON_MIN_PHASE0_PASS_READY_FOR_ROLLOUT' if gate['pass'] else 'COMMON_MIN_PHASE0_FAILED_NO_ROLLOUT';(art/'phase0_summary.json').write_text(json.dumps({'gate':gate,'states':rows},indent=2,sort_keys=True)+'\n');(art/'decision.json').write_text(json.dumps({'decision':decision,'gate':gate,'rollout_started':False},indent=2)+'\n');(art/'status'/('phase0.pass' if gate['pass'] else 'phase0.fail')).write_text(decision+'\n');print(json.dumps(gate,indent=2))
if __name__=='__main__':main()
