#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,math,os,statistics,sys
from pathlib import Path
import torch,yaml
WS=Path(__file__).resolve().parents[2];sys.path[:0]=[str(WS/'LIBERO'),str(WS/'lerobot/src'),str(WS)]
from research.coreact_closed_loop.guidance import tensor_sha256
from research.coreact_closed_loop.runtime import load_policy_and_processors,make_task_env,prepare
from research.coreact_dynamic_core.dynamic_guidance import sample_dynamic_core_actions
SELECTORS=('random','attention','instability','combined')
def main():
 p=argparse.ArgumentParser();p.add_argument('--workspace',type=Path,required=True);p.add_argument('--artifact',type=Path,required=True);a=p.parse_args();w=a.workspace.resolve();art=a.artifact.resolve();protocol=yaml.safe_load((art/'protocol.lock.yaml').read_text())
 os.environ.setdefault('HF_HOME',str(w/'task1/.hf-cache'));os.environ.setdefault('TRANSFORMERS_CACHE',str(w/'task1/.hf-cache/hub'));os.environ['MUJOCO_GL']='egl';cfg,policy,pre,post=load_policy_and_processors(w);means=torch.load(w/'artifacts/coreact_exploration_v8_20260807_002951/modality_means.pt',weights_only=True,map_location='cpu')['visual_position_mean'];from libero.libero import benchmark;suite=benchmark.get_benchmark_dict()['libero_spatial']();rows=[];repeat_pass=vanilla_parity=True
 for task in protocol['tasks']:
  language=suite.get_task(task).language
  for init in protocol['init_state_ids']:
   env,env_pre,env_post=make_task_env('libero_spatial',task,cfg)
   try:
    inner=env.envs[0];inner.init_state_id=init;obs,_=env.reset(seed=140000000+task*1000+init);batch=prepare(policy,pre,env_pre,obs,language);gen=torch.Generator(device=batch['state'].device).manual_seed(202608120000+task*1000+init);noise=torch.randn((1,cfg.chunk_size,cfg.max_action_dim),generator=gen,device=batch['state'].device,dtype=batch['state'].dtype);state=[]
    for selector in SELECTORS:
     out,tr=sample_dynamic_core_actions(policy.model,batch['images'],batch['image_masks'],batch['lang_tokens'],batch['lang_masks'],batch['state'],noise,means,selector=selector,selection_seed=20260812+task*100+init);steps=tr['step_traces'];state.append({'selector':selector,'selected_indices':tr['selected_indices'],'changed_indices':tr['changed_indices'],'attention_top_indices':tr['attention_top_indices'],'instability_top_indices':tr['instability_top_indices'],'combined_top_indices':tr['combined_top_indices'],'attn_instability_overlap':tr['attn_instability_overlap'],'attn_instability_jaccard':tr['attn_instability_overlap']/(16-tr['attn_instability_overlap']),'attn_combined_overlap':tr['attn_combined_overlap'],'instability_combined_overlap':tr['instability_combined_overlap'],'raw_delta_mean':statistics.mean(x['raw_delta_norm'] for x in steps),'postclip_rms':math.sqrt(statistics.mean(x['applied_guidance_norm']**2 for x in steps)),'clipping_fraction':statistics.mean(x['clipped'] for x in steps),'output_sha256':tensor_sha256(out),'clean_flow_final_sha256':tr['clean_flow_final_sha256'],'prefix_sha256':tr['prefix_sha256'],'negative_prefix_sha256':tr['negative_prefix_sha256'],'finite':tr['all_output_finite'],'protected':tr['protected_tokens_untouched'],'flow_attention_layer_counts':tr['flow_attention_layer_counts']})
    if task==protocol['tasks'][0] and init==protocol['init_state_ids'][0]:
     vanilla=policy.model.sample_actions(batch['images'],batch['image_masks'],batch['lang_tokens'],batch['lang_masks'],batch['state'],noise=noise);vanilla_parity=state[0]['clean_flow_final_sha256']==tensor_sha256(vanilla);out2,tr2=sample_dynamic_core_actions(policy.model,batch['images'],batch['image_masks'],batch['lang_tokens'],batch['lang_masks'],batch['state'],noise,means,selector='combined',selection_seed=20260812+task*100+init);ref=next(x for x in state if x['selector']=='combined');repeat_pass=ref['selected_indices']==tr2['selected_indices'] and ref['output_sha256']==tensor_sha256(out2)
    payload={'task_id':task,'init_state_id':init,'selectors':state};(art/'states'/f'task{task:02d}__init{init:02d}.json').write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');rows.append(payload);print(f'task={task} init={init}',flush=True)
   finally:env.close()
 flat=[x for r in rows for x in r['selectors']];attn=[x for x in flat if x['selector']=='attention'];ratios={s:statistics.median([next(x for x in r['selectors'] if x['selector']==s)['postclip_rms']/next(x for x in r['selectors'] if x['selector']=='attention')['postclip_rms'] for r in rows]) for s in ('random','instability','combined')};j=statistics.median([next(x for x in r['selectors'] if x['selector']=='attention')['attn_instability_jaccard'] for r in rows]);gate={'exact8_protected':all(len(x['selected_indices'])==8 and sorted(x['selected_indices'])==sorted(x['changed_indices']) and x['protected'] for x in flat),'finite':all(x['finite'] for x in flat),'clean_hash_identity':all(len({x['clean_flow_final_sha256'] for x in r['selectors']})==1 for r in rows),'vanilla_clean_parity':vanilla_parity,'deterministic_repeat':repeat_pass,'median_attn_instability_jaccard':j,'jaccard_pass':j<=.75,'postclip_rms_ratios_to_attention':ratios,'magnitude_pass':all(.5<=x<=2 for x in ratios.values())};gate['pass']=all(gate[k] for k in ('exact8_protected','finite','clean_hash_identity','vanilla_clean_parity','deterministic_repeat','jaccard_pass','magnitude_pass'));(art/'phase0_summary.json').write_text(json.dumps({'gate':gate,'states':rows},indent=2,sort_keys=True)+'\n');decision='PHASE0_DYNAMIC_SELECTOR_PASS_READY_FOR_ROLLOUT' if gate['pass'] else 'PHASE0_DYNAMIC_SELECTOR_FAILED_NO_ROLLOUT';(art/'decision.json').write_text(json.dumps({'decision':decision,'gate':gate,'rollout_started':False},indent=2)+'\n');(art/'status'/('phase0.pass' if gate['pass'] else 'phase0.fail')).write_text(decision+'\n');print(json.dumps(gate,indent=2))
if __name__=='__main__':main()
